/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_3_00_01_59/packages/ti/mcu/msp430/csl/interrupt_vectors/InterruptVectors_init.xdt
 */
#include <msp430.h>
#include "../MSP430PORT_DEF.h"
#include "../main.h"

/* USER CODE START (section: InterruptVectors_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: InterruptVectors_init_c_prologue) */

/*
 *  ======== InterruptVectors_graceInit ========
 */
void InterruptVectors_graceInit(void)
{
}


/* Interrupt Function Prototypes */



/*
 *  ======== PORT2 Interrupt Service Routine ========
 *
 * Here are several important notes on using PORTx interrupt Handler:
 *
 * 1. User must explicitly clear the port interrupt flag before exiting
 *
 *    PxIFG &= ~(BITy);
 *
 * 2. User could also exit from low power mode and continue with main
 *    program execution by using the following instruction before exiting
 *    this interrupt handler.
 *
 *    __bic_SR_register_on_exit(LPMx_bits);
 *
 */
#pragma vector=PORT2_VECTOR
__interrupt void PORT2_ISR_HOOK(void)
{
    /* USER CODE START (section: PORT2_ISR_HOOK) */
    /* replace this comment with your code */
    /* USER CODE END (section: PORT2_ISR_HOOK) */
  INT32U cnt_t=0;
  _DINT();
  if((P2IFG&BIT0)==BIT0)
  {
    P2IFG &=~ BIT0;
  }
  else if((P2IFG&BIT1)==BIT1)
  {
    P2IFG &=~ BIT1;
  } 
  else if((P2IFG&BIT6)==BIT6)
  {
    do
    {
      cnt_t++;
    }while((!(P2IN&BIT6))&&(cnt_t<100000));
    if(cnt_t>90000)
    {
      MOTOD1_TG; MOTOD2_TG;    //超时转换电机方向
      Moto1stChange=true;Moto2ndChange=true;
    }
    else
    {
      if(PwmWidthNum<20) PwmWidthNum++;   
    }
    P2IFG&=~BIT6;
  }
  else if((P2IFG&BIT7)==BIT7)
  {
    do
    {
      cnt_t++;
    }while((!(P2IN&BIT7))&&(cnt_t<100000));
    if(cnt_t>90000)
    {
      PwmWidthNum=0;
    }
    else
    {
      if(PwmWidthNum>0)
      {
        PwmWidthNum--;
      }
      P2IFG&=~BIT7;
    }
  }
  else
  {
    P2IFG = 0;
  }
  P2IFG = 0;
  cnt_t=0; 
  _EINT();
  __bic_SR_register_on_exit(LPM0_bits);
  
}

#pragma vector=PORT1_VECTOR
__interrupt void PORT1_ISR_HOOK(void)
{
    /* USER CODE START (section: PORT2_ISR_HOOK) */
    /* replace this comment with your code */
    /* USER CODE END (section: PORT2_ISR_HOOK) */
  if((P1IFG&BIT3)==BIT3)
  {
    StopFlag = true;
  }
  P1IFG = 0;
  __bic_SR_register_on_exit(LPM0_bits);
}

/*
 *  ======== NMI_VECTOR Interrupt Service Routine ========
 *
 *  You can check which interrupt flag was triggered here.
 *  Copy and paste the following function as desired.
 *
    if (IFG1 & NMIIFG) {

    }
    else if (IFG1 & OFIFG) {

    }
    else if (IFG1 & ACCVIFG) {

    }
 *
 */
#pragma vector=NMI_VECTOR
__interrupt void NMI_ISR_HOOK(void)
{
    /* USER CODE START (section: NMI_ISR_HOOK) */
    /* replace this comment with your code */
    /* USER CODE END (section: NMI_ISR_HOOK) */
}
